language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t csteel/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true csteel/react-test npm test
after_success:
    - docker build -t csteel/multi-client ./client
    - docker build -t csteel/multi-nginx ./nginx
    - docker build -t csteel/multi-server ./server
    - docker build -t csteel/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push csteel/multi-client
    - docker push csteel/multi-nginx
    - docker push csteel/multi-server
    - docker push csteel/multi-worker